import './style.css';
import { createIcons, ShieldCheck, Search, Plus, Upload, FileText, Users, LockKeyhole, ChevronRight, ArrowUp, X, Trash2, MessageCircle, BookOpen, Sparkles, Check, Download, CircleHelp, LoaderCircle, Pencil, RotateCcw } from 'lucide';
import { initialState, loadState, saveState, removeMember, removePolicy } from './storage';
import { answerQuestion } from './retrieval';
import { readPDF, drawPage } from './pdf';
import { enableAI, disableAI, explainWithAI } from './ai';
import type { FamilyState, Evidence, Policy } from './types';
const app=document.querySelector<HTMLDivElement>('#app')!;
let state:FamilyState=initialState(),busy=false,status='',notice='',dbReady=false,ocr=false,aiReady=false,aiLoading=false,selectedPolicy='all',mobileTab='chat';
let aborter:AbortController|undefined;let activeEvidence:Evidence|undefined;let saveQueue=Promise.resolve();
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const icon=(name:string)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const dis=()=>busy?'disabled':'';
const current=()=>state.members.find(m=>m.id===state.activeId)!;
const policies=()=>state.policies.filter(p=>p.memberId===state.activeId);
const messages=()=>state.messages.filter(m=>m.memberId===state.activeId);
const prompts=['보장범위를 정리해 줘','보험금을 못 받는 경우는?','입원비는 얼마나 보장돼?','청구할 때 어떤 서류가 필요해?'];
function icons(){createIcons({icons:{ShieldCheck,Search,Plus,Upload,FileText,Users,LockKeyhole,ChevronRight,ArrowUp,X,Trash2,MessageCircle,BookOpen,Sparkles,Check,Download,CircleHelp,LoaderCircle,Pencil,RotateCcw},attrs:{'stroke-width':1.7}});}
function toast(text:string){notice=text;render();}
async function persist(next:FamilyState){
  if(!dbReady){toast('이 브라우저에 저장할 수 없습니다. 일반 브라우저 창에서 다시 열어 주세요.');return false;}
  try{saveQueue=saveQueue.then(()=>saveState(next));await saveQueue;state=next;return true;}catch{saveQueue=Promise.resolve();toast('저장하지 못했습니다. 저장 공간 또는 브라우저 설정을 확인해 주세요. 변경은 적용하지 않았습니다.');return false;}
}
function evidenceCard(e:Evidence,i:number){return `<button class="evidence-card" data-evidence="${esc(e.id)}"><span class="evidence-number">${i+1}</span><span><strong>${esc(e.policyName)}</strong><span class="evidence-snippet">${esc(e.text.slice(0,130))}${e.text.length>130?'…':''}</span><small>PDF ${e.page}페이지 ${e.ocr?'· 문자 인식':''}</small></span>${icon('chevron-right')}</button>`;}
function readyMarkup(ps:Policy[]){return `<div class="ready-state"><span class="welcome-icon">${icon('check')}</span><p class="eyebrow">READY TO READ</p><h2>약관을 읽었어요.<br>무엇이 궁금하세요?</h2><p>${esc(current().name)}의 약관 ${ps.length}개에서 근거를 찾아드릴게요.</p><div class="ready-prompts">${prompts.map(q=>`<button data-prompt="${esc(q)}" ${dis()}>${icon('message-circle')}<span>${esc(q)}</span>${icon('chevron-right')}</button>`).join('')}</div><small>특정 보험만 궁금하다면 위에서 약관을 선택해 주세요.</small></div>`;}
function answerMarkup(m:ReturnType<typeof messages>[number]){
  const a=m.answer;return `<div class="question-bubble">${esc(m.question)}</div><article class="answer"><div class="answer-heading"><span class="bot-icon">${icon('search')}</span><strong>약관돋보기</strong><span class="tag">원문 근거</span></div><p>${esc(a.intro)}</p>${a.evidence.map((e,i)=>`<button class="quote" data-evidence="${esc(e.id)}"><span class="quote-heading">[${i+1}] ${esc(e.policyName)} · PDF ${e.page}페이지 ${e.ocr?'· 문자 인식 결과 (원문 대조 필요)':''}</span><span>${esc(e.text.slice(0,550))}${e.text.length>550?'…':''}</span><small>원문 페이지 확인 ${icon('book-open')}</small></button>`).join('')}${a.cautions.length?`<div class="caution"><strong>함께 확인할 제한 조건</strong><p>같은 약관의 면책·감액·자기부담 조항입니다. 질문에 대한 직접 근거와 구분해서 읽어 주세요.</p>${a.cautions.map((e,i)=>`<button data-evidence="${esc(e.id)}">[${a.evidence.length+i+1}] ${esc(e.policyName)} · PDF ${e.page}페이지 ${icon('chevron-right')}</button>`).join('')}</div>`:''}${a.aiText?`<details class="ai-explanation" open><summary>${icon('sparkles')} 무료 AI 설명 · 원문 대조 필요</summary><p>${esc(a.aiText).replace(/\n/g,'<br>')}</p><small>기기 내 소형 AI의 설명에는 오류가 있을 수 있습니다. 위 원문을 우선해 주세요.</small></details>`:''}${a.aiError?`<p class="subtle">${esc(a.aiError)}</p>`:''}<p class="answer-foot">약관에 기재된 조건입니다. 실제 가입 담보·가입금액·보장개시일은 보험증권과 함께 확인해 주세요.</p></article>`;
}
function render(){
  const ps=policies(),ms=messages(),member=current();
  const refs=activeEvidence?[activeEvidence]:(ms.at(-1)?[...ms.at(-1)!.answer.evidence,...ms.at(-1)!.answer.cautions]:[]);
  app.innerHTML=`<header class="topbar"><a class="brand" href="/" aria-label="약관돋보기 홈"><span class="brand-mark">${icon('shield-check')}</span><span>약관돋보기<small>우리 가족 보험 읽기</small></span></a><div class="top-actions"><span class="privacy-pill">${icon('lock-keyhole')} 내 기기에서만 안전하게</span><button class="icon-btn" data-action="help" aria-label="이용 안내">${icon('circle-help')}</button><span class="free-label">100% 무료</span></div></header>
  <div class="workspace"><aside class="sidebar ${mobileTab==='family'?'mobile-active':''}" aria-label="가족과 약관 관리"><div class="section-title"><span>${icon('users')} 우리 가족</span><button class="icon-btn" data-action="add-member" aria-label="가족 추가" ${dis()}>${icon('plus')}</button></div><div class="family-list">${state.members.map((m,i)=>`<button class="family ${m.id===state.activeId?'selected':''}" data-member="${esc(m.id)}" ${dis()}><span class="avatar color-${i%4}">${esc(m.name.slice(0,1))}</span><span class="family-name"><strong>${esc(m.name)}</strong><small>${esc(m.relation)} · 약관 ${state.policies.filter(p=>p.memberId===m.id).length}개</small></span>${m.id===state.activeId?'<span class="selected-dot"></span>':''}</button>`).join('')}</div><button class="text-btn member-manage" data-action="edit-member" ${dis()}>${icon('pencil')} ${esc(member.name)} 정보 관리</button>
  <div class="sidebar-divider"></div><div class="section-title"><span>보험 약관 <b>${ps.length}</b></span></div><div class="policy-list">${ps.length?ps.map(p=>`<div class="policy-item"><button data-policy="${esc(p.id)}" title="${esc(p.name)}" ${dis()}>${icon('file-text')}<span><strong>${p.demo?'<em>예시</em> ':''}${esc(p.name)}</strong><small>${p.pages.length}페이지 · ${p.unreadable.length?'읽기 미완료':'읽기 완료'}</small></span></button><button class="icon-btn delete-doc" data-delete-policy="${esc(p.id)}" aria-label="${esc(p.name)} 삭제" ${dis()}>${icon('x')}</button></div>`).join(''):'<p class="sidebar-empty">아직 등록된 약관이 없어요.</p>'}</div>
  <button class="upload-small" data-action="upload" ${dis()}>${icon('plus')} ${esc(member.name)}의 PDF 추가</button><label class="ocr-option"><input id="ocr-option" type="checkbox" ${ocr?'checked':''} ${dis()}> 스캔 PDF 문자 인식 <span class="tag">무료</span></label><p class="ocr-hint">문자 인식은 파일당 최대 50페이지. 흐릿한 글자·표는 원문과 대조해 주세요.</p><div class="local-note">${icon('lock-keyhole')}<p>가족 명단과 PDF는 이 브라우저에만 저장돼요.<span>다른 기기와 자동으로 공유되지 않아요.</span></p></div></aside>
  <main class="main-panel ${mobileTab==='chat'?'mobile-active':''}"><div class="conversation-header"><div><div class="eyebrow">FAMILY INSURANCE NOTE</div><h1>${esc(member.name)}의 보험 이야기</h1></div><span class="mode-badge">${icon('check')} ${aiReady?'무료 AI + 원문':'원문 근거 모드'}</span></div>
  <div class="scope-row"><label for="policy-scope">질문할 약관</label><select id="policy-scope" ${dis()}><option value="all">${esc(member.name)}의 전체 약관 (${ps.length}개)</option>${ps.map(p=>`<option value="${esc(p.id)}" ${selectedPolicy===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>${ms.length?`<button class="icon-btn" data-action="clear-chat" aria-label="현재 가족 대화 지우기" ${dis()}>${icon('rotate-ccw')}</button>`:''}</div>
  ${notice?`<div class="notice" role="alert"><span>${esc(notice)}</span><button class="icon-btn" data-action="dismiss-notice" aria-label="알림 닫기">${icon('x')}</button></div>`:''}
  ${ps.some(p=>p.pages.some(page=>page.ocr))?`<div class="partial-warning" role="status">문자 인식 자료가 포함되어 있습니다. 특히 금액·기간·횟수는 잘못 읽힐 수 있으니 PDF 원문을 확인하세요.</div>`:''}
  ${ps.some(p=>p.unreadable.length)?`<div class="partial-warning" role="status">읽지 못한 페이지가 있습니다: ${ps.filter(p=>p.unreadable.length).map(p=>`${esc(p.name)} (${p.unreadable.slice(0,15).join(', ')}${p.unreadable.length>15?' 외':''}페이지)`).join(' / ')}. 이 문서의 답변은 불완전할 수 있습니다.</div>`:''}
  <div class="conversation ${ms.length?'has-messages':''}" id="conversation" aria-live="polite">${ms.length?ms.map(answerMarkup).join(''):ps.length?readyMarkup(ps):`<div class="welcome"><div class="welcome-icon">${icon('search')}<span>?</span></div><p class="welcome-kicker">보험은 가까이, 어려운 말은 멀리.</p><h2>복잡한 약관,<br><span>우리 가족 기준으로.</span></h2><p class="welcome-description">약관 PDF를 넣고 편하게 물어보세요.<br>보장 내용부터 작은 예외까지, 근거를 함께 찾아드려요.</p><button class="dropzone" id="dropzone" data-action="upload" ${dis()}><span class="upload-icon">${icon('upload')}</span><strong>보험 약관 PDF 넣기</strong><span>여기에 끌어 놓거나 눌러서 선택하세요</span><small>파일당 20MB · 최대 500페이지 · 여러 파일 가능</small></button><button class="sample-link" data-action="sample" ${dis()}>PDF가 없다면, 가상 약관으로 체험하기 ${icon('chevron-right')}</button><div class="question-starters"><span>이렇게 물어보세요</span><div>${prompts.slice(0,3).map((q,i)=>`<button data-prompt="${esc(q)}" ${dis()}>${icon(['shield-check','search','file-text'][i])}${esc(q)}</button>`).join('')}</div></div></div>`}${busy?`<div class="progress" role="status">${icon('loader-circle')}<span>${esc(status)}</span>${aborter?'<button data-action="cancel">취소</button>':''}</div>`:''}</div>
  <div class="composer-area">${ps.length&&ms.length?`<div class="quick-prompts">${prompts.slice(0,2).map(q=>`<button data-prompt="${esc(q)}" ${dis()}>${esc(q)}</button>`).join('')}</div>`:''}<form id="ask-form"><label class="sr-only" for="question">보험 약관 질문</label><textarea id="question" rows="1" maxlength="1200" placeholder="${ps.length?`${esc(member.name)}의 보험에 대해 물어보세요…`:'먼저 약관 PDF를 넣어 주세요'}" ${!ps.length||busy?'disabled':''}></textarea><button type="submit" class="send-btn" aria-label="질문 보내기" ${!ps.length||busy?'disabled':''}>${icon('arrow-up')}</button></form><div class="composer-foot"><span>${icon('lock-keyhole')} PDF와 질문은 서버로 전송하지 않아요</span><button data-action="ai" ${busy||aiLoading?'disabled':''}>${icon('sparkles')}${aiReady?'무료 AI 켜짐':'무료 AI 설명 켜기'}</button></div><p class="disclaimer">약관 이해를 돕는 참고 정보입니다. 실제 보험금 지급 여부는 보험사 심사를 통해 결정됩니다.</p></div></main>
  <aside class="sources-panel ${mobileTab==='sources'?'mobile-active':''}" aria-label="근거 원문"><div class="section-title"><span>${icon('book-open')} 근거 노트</span><span class="count">${refs.length}</span></div><p class="source-description">답변의 출처를 직접 확인하세요.</p>${refs.length?refs.map(evidenceCard).join(''):`<div class="source-empty"><div class="paper-illustration"><span></span><span></span><span></span><i>${icon('check')}</i></div><strong>답변 옆에, 근거도 함께</strong><p>질문하면 관련 조항과<br>PDF 페이지가 여기에 모여요.</p></div>`}<div class="read-guide"><span>약관 읽기 TIP</span><h3>보장만큼 중요한<br>세 가지를 확인해요.</h3><ol><li><b>01</b><span>보장하지 않는 경우<small>면책·제외 조건</small></span></li><li><b>02</b><span>언제부터, 얼마까지<small>보장개시일·감액·지급 한도</small></span></li><li><b>03</b><span>실제로 가입한 담보<small>보험증권의 특약·가입금액</small></span></li></ol></div></aside></div>
  <nav class="mobile-nav" aria-label="화면 선택">${[['family','users','가족·약관'],['chat','message-circle','질문하기'],['sources','book-open','근거 노트']].map(([tab,ic,label])=>`<button class="${mobileTab===tab?'active':''}" data-tab="${tab}">${icon(ic)}${label}</button>`).join('')}</nav><input type="file" id="pdf-input" accept="application/pdf,.pdf" multiple hidden><dialog id="modal"></dialog>`;
  icons();bind();
}
function modal(html:string){const d=document.querySelector<HTMLDialogElement>('#modal')!;d.className='';d.innerHTML=`<button class="icon-btn modal-close" aria-label="닫기">${icon('x')}</button>${html}`;d.querySelector('.modal-close')!.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});d.showModal();icons();return d;}
function memberForm(edit=false){
  const m=current();const d=modal(`<div class="modal-icon">${icon('users')}</div><h2>${edit?'가족 정보 관리':'우리 가족 추가'}</h2><p>이름이나 별명만으로 충분해요.</p><form id="member-form"><label>이름 또는 별명<input name="name" maxlength="24" required value="${edit?esc(m.name):''}" placeholder="예: 엄마" autocomplete="off"></label><label for="member-relation">관계</label><select id="member-relation" name="relation">${['본인','배우자','부모','자녀','형제·자매','가족','기타'].map(v=>`<option ${edit&&m.relation===v?'selected':''}>${v}</option>`).join('')}</select><button class="primary" type="submit">${edit?'변경 저장':'가족 추가'}</button></form>${edit&&state.members.length>1?'<button class="danger-link" id="delete-member">이 가족과 연결된 자료 삭제</button>':''}`);
  d.querySelector('form')!.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target as HTMLFormElement);const name=String(f.get('name')).trim();if(!name)return;const relation=String(f.get('relation'));if(state.members.length>=30&&!edit){toast('가족은 최대 30명까지 등록할 수 있습니다.');return;}const id=edit?m.id:crypto.randomUUID();const next={...state,members:edit?state.members.map(x=>x.id===id?{...x,name,relation}:x):[...state.members,{id,name,relation}],activeId:id};if(await persist(next)){selectedPolicy='all';activeEvidence=undefined;d.close();render();}});
  d.querySelector('#delete-member')?.addEventListener('click',()=>{d.close();confirmDelete(`${m.name}의 명단, 약관, 대화를 모두 삭제할까요?`,async()=>{await persist(removeMember(state,m.id));selectedPolicy='all';activeEvidence=undefined;render();});});
}
function confirmDelete(text:string,callback:()=>Promise<void>){const d=modal(`<h2>자료 삭제</h2><p>${esc(text)}</p><p class="subtle">이 브라우저에서 삭제되며 되돌릴 수 없습니다.</p><button class="danger" id="confirm-delete">삭제하기</button>`);d.querySelector('#confirm-delete')!.addEventListener('click',async()=>{d.close();await callback();});}
async function importFiles(files:File[],demo=false){
  if(busy||!dbReady)return;busy=true;notice='';const memberId=state.activeId;aborter=new AbortController();const signal=aborter.signal;let added=0;
  try{for(const file of files){if(signal.aborted)break;if(state.policies.length>=50)throw new Error('전체 약관은 최대 50개까지 저장할 수 있습니다.');status='PDF를 준비하고 있어요';render();const extracted=await readPDF(file,s=>{status=s;const el=document.querySelector('.progress span');if(el)el.textContent=s;},signal,ocr);if(signal.aborted)break;
    if(state.policies.some(p=>p.memberId===memberId&&p.fingerprint===extracted.fingerprint)){notice=`${file.name}: 이 가족에게 이미 등록된 약관입니다.`;continue;}
    const p:Policy={id:crypto.randomUUID(),memberId,name:file.name,...extracted,blob:file,addedAt:new Date().toISOString(),demo};
    if(!(await persist({...state,policies:[...state.policies,p]})))break;added++;
  }}catch(e){notice=e instanceof DOMException&&e.name==='AbortError'?'읽기를 취소했습니다. 이미 저장한 파일은 유지됩니다.':e instanceof Error?e.message:'PDF를 읽지 못했습니다.';}finally{busy=false;aborter=undefined;status='';if(added&&!notice)notice=`${current().name}의 약관 ${added}개를 저장했습니다. 이제 질문해 보세요.`;render();}
}
async function ask(question:string){
  if(busy)return;question=question.trim();if(!question)return;if(!policies().length){toast('먼저 PDF를 넣거나 가상 약관으로 체험해 주세요.');return;}
  const ps=policies().filter(p=>selectedPolicy==='all'||p.id===selectedPolicy);if(!ps.length){toast('질문할 약관을 선택해 주세요.');return;}
  busy=true;status='질문과 관련된 조항을 찾고 있어요';notice='';const memberId=state.activeId;
  const answer=answerQuestion(question,ps,messages().at(-1)?.question);if(answer.evidence.some(e=>e.ocr)){answer.intro='문자 인식 결과에서 관련 조항을 찾았습니다. 숫자와 단어가 원문과 다를 수 있으니 PDF 페이지를 열어 반드시 대조해 주세요.';answer.aiError='문자 인식 자료는 오인식 가능성이 있어 AI 설명을 생략합니다.';}const m={id:crypto.randomUUID(),memberId,question,answer,time:new Date().toISOString()};
  render();
  if(aiReady&&!answer.missing&&![...answer.evidence,...answer.cautions].some(e=>e.ocr)){status='기기 내 무료 AI가 원문을 읽고 있어요';render();try{const text=await explainWithAI(question,answer);if(text)answer.aiText=text;else answer.aiError='AI 설명을 만들지 못해 원문 근거를 표시합니다.';}catch{answer.aiError='이 기기에서 AI 설명을 완료하지 못했습니다. 원문 근거를 확인해 주세요.';aiReady=false;disableAI();}}
  await persist({...state,messages:[...state.messages,m].slice(-200)});busy=false;activeEvidence=undefined;render();const conversation=document.querySelector('#conversation');conversation?.scrollTo({top:conversation.scrollHeight,behavior:'smooth'});
}
function allEvidence(){return state.messages.filter(m=>m.memberId===state.activeId).flatMap(m=>[...m.answer.evidence,...m.answer.cautions]);}
async function showEvidence(e:Evidence){activeEvidence=e;const p=policies().find(p=>p.id===e.policyId);if(!p)return;const d=modal(`<div class="eyebrow">SOURCE DOCUMENT</div><h2>${esc(p.name)}</h2><div class="page-bar"><button id="prev-page" class="secondary">이전</button><span id="page-label"></span><button id="next-page" class="secondary">다음</button><button id="download-pdf" class="icon-btn" aria-label="원본 PDF 다운로드">${icon('download')}</button></div><p class="subtle">페이지 번호는 PDF 파일 순서입니다. 인쇄된 쪽수와 다를 수 있습니다.</p><div class="pdf-preview"><canvas id="pdf-canvas" aria-label="PDF 원문 페이지"></canvas></div><details><summary>추출한 텍스트 확인</summary><pre id="page-text"></pre></details>`);d.classList.add('document-modal');let pageNo=e.page;
  const draw=async()=>{const prev=d.querySelector<HTMLButtonElement>('#prev-page')!,next=d.querySelector<HTMLButtonElement>('#next-page')!;prev.disabled=true;next.disabled=true;d.querySelector('#page-label')!.textContent=`PDF ${pageNo} / ${p.pages.length}페이지`;d.querySelector('#page-text')!.textContent=p.pages[pageNo-1].text||'읽지 못한 페이지입니다.';try{await drawPage(p.blob,pageNo,d.querySelector('canvas')!);}catch{d.querySelector('.pdf-preview')!.textContent='미리보기를 열지 못했습니다. 원본 PDF를 내려받아 확인해 주세요.';}finally{prev.disabled=pageNo<=1;next.disabled=pageNo>=p.pages.length;}};
  d.querySelector('#prev-page')!.addEventListener('click',()=>{pageNo--;void draw();});d.querySelector('#next-page')!.addEventListener('click',()=>{pageNo++;void draw();});d.querySelector('#download-pdf')!.addEventListener('click',()=>download(p.blob,p.name));await draw();
}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function aiDialog(){
  if(aiLoading)return;
  if(aiReady){aiReady=false;disableAI();render();return;}
  const d=modal(`<div class="modal-icon">${icon('sparkles')}</div><h2>무료 AI 설명</h2><p>약관 원문을 바탕으로 소형 AI가 쉬운 말로 설명해요.</p><ul class="help-list"><li>API 키와 사용료가 없습니다.</li><li>첫 실행 시 모델 수백 MB를 내려받습니다. 데이터 요금이 걱정되면 Wi-Fi를 사용하세요.</li><li>WebGPU 지원 브라우저와 여유 메모리가 필요합니다. 모델은 Hugging Face에서 내려받고, PDF·질문은 기기 밖으로 보내지 않습니다.</li><li>AI는 금액·조건을 잘못 설명할 수 있습니다. 원문 근거를 함께 확인해 주세요.</li></ul><button class="primary" id="enable-ai">무료 모델 내려받고 켜기</button><p id="ai-status" role="status"></p>`);
  d.querySelector('#enable-ai')!.addEventListener('click',async()=>{aiLoading=true;const btn=d.querySelector<HTMLButtonElement>('#enable-ai')!;btn.disabled=true;try{await enableAI(s=>{d.querySelector('#ai-status')!.textContent=s;});aiReady=true;d.close();notice='무료 AI가 준비되었습니다. 다음 질문부터 원문과 함께 설명합니다.';}catch{notice='무료 AI를 시작하지 못했습니다. WebGPU·저장 공간·네트워크를 확인해 주세요. 원문 근거 모드는 계속 사용할 수 있습니다.';}finally{aiLoading=false;render();}});
}
function bind(){
  document.querySelectorAll<HTMLButtonElement>('[data-member]').forEach(el=>el.addEventListener('click',async()=>{if(await persist({...state,activeId:el.dataset.member!})){selectedPolicy='all';activeEvidence=undefined;notice='';render();}}));
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(el=>el.addEventListener('click',()=>{mobileTab=el.dataset.tab!;render();}));
  document.querySelectorAll<HTMLButtonElement>('[data-prompt]').forEach(el=>el.addEventListener('click',()=>void ask(el.dataset.prompt!)));
  document.querySelectorAll<HTMLButtonElement>('[data-evidence]').forEach(el=>el.addEventListener('click',()=>{const e=allEvidence().find(e=>e.id===el.dataset.evidence);if(e)void showEvidence(e);}));
  document.querySelectorAll<HTMLButtonElement>('[data-policy]').forEach(el=>el.addEventListener('click',()=>{const p=policies().find(p=>p.id===el.dataset.policy)!;void showEvidence({id:'preview',policyId:p.id,policyName:p.name,page:1,text:p.pages[0].text,score:0});}));
  document.querySelectorAll<HTMLButtonElement>('[data-delete-policy]').forEach(el=>el.addEventListener('click',()=>{const p=policies().find(p=>p.id===el.dataset.deletePolicy)!;confirmDelete(`${p.name}과 이 문서를 인용한 대화를 삭제할까요?`,async()=>{await persist(removePolicy(state,p.id));selectedPolicy='all';activeEvidence=undefined;render();});}));
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(el=>el.addEventListener('click',()=>{
    switch(el.dataset.action){case'add-member':memberForm();break;case'edit-member':memberForm(true);break;case'upload':document.querySelector<HTMLInputElement>('#pdf-input')!.click();break;case'dismiss-notice':notice='';render();break;case'cancel':aborter?.abort();break;case'sample':void (async()=>{try{const r=await fetch('/sample-policy.pdf');if(!r.ok)throw new Error();await importFiles([new File([await r.blob()],'체험용_가상보험약관.pdf',{type:'application/pdf'})],true);}catch{toast('체험 PDF를 불러오지 못했습니다. 다시 시도해 주세요.');}})();break;case'ai':void aiDialog();break;case'clear-chat':confirmDelete(`${current().name}의 대화를 지울까요? 약관은 유지됩니다.`,async()=>{await persist({...state,messages:state.messages.filter(m=>m.memberId!==state.activeId)});activeEvidence=undefined;render();});break;case'help':modal(`<h2>약관돋보기 이용 안내</h2><ol class="help-list"><li>가족을 추가하고 대상 가족을 선택하세요.</li><li>보험약관·특약 PDF를 넣으세요. 여러 보험을 함께 저장할 수 있습니다.</li><li>질문할 약관을 선택한 뒤 보장·면책·한도·청구 내용을 물어보세요.</li><li>답변의 근거를 누르면 PDF 원문 페이지를 확인할 수 있습니다.</li></ol><h3>저장과 개인정보</h3><p>명단, PDF, 대화는 이 기기의 현재 브라우저에 저장됩니다. 서버 전송, 계정, 자동 동기화는 없습니다. 공용 기기에서는 사용 후 가족 자료를 삭제하세요. 브라우저 데이터 삭제·시크릿 창 종료 시 자료가 사라질 수 있으니 원본 PDF를 별도로 보관하세요.</p><h3>답변 범위</h3><p>기본 모드는 관련 원문을 찾는 검색 기반 답변입니다. 전체 약관의 법적 해석이나 보험금 지급을 확정하지 않습니다. AI 설명은 선택 기능입니다. 실제 가입 여부는 보험증권과 보험사에서 확인하세요.</p><h3>스캔·표·대용량 문서</h3><p>문자 인식을 켜면 글자가 없는 페이지를 파일당 최대 50페이지 읽습니다. 표의 행·열, 작은 글씨, 숫자는 잘못 읽힐 수 있습니다. 읽지 못한 페이지가 있으면 경고를 표시합니다.</p><a class="repo-link" href="https://github.com/kimkirik/yakgwan-bot" target="_blank" rel="noopener noreferrer">GitHub 소스 코드</a>`);break;}
  }));
  document.querySelector('#ocr-option')!.addEventListener('change',e=>{ocr=(e.target as HTMLInputElement).checked;});
  document.querySelector('#policy-scope')!.addEventListener('change',e=>{selectedPolicy=(e.target as HTMLSelectElement).value;});
  document.querySelector('#pdf-input')!.addEventListener('change',e=>{const input=e.target as HTMLInputElement;void importFiles(Array.from(input.files??[]));});
  document.querySelector('#ask-form')!.addEventListener('submit',e=>{e.preventDefault();void ask(document.querySelector<HTMLTextAreaElement>('#question')!.value);});
  document.querySelector('#question')!.addEventListener('keydown',e=>{const k=e as KeyboardEvent;if(k.key==='Enter'&&!k.shiftKey&&!k.isComposing){k.preventDefault();void ask((k.target as HTMLTextAreaElement).value);}});
  const drop=document.querySelector('#dropzone');drop?.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over');});drop?.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop?.addEventListener('drop',e=>{e.preventDefault();void importFiles(Array.from((e as DragEvent).dataTransfer?.files??[]));});
}
try{state=await loadState();dbReady=true;}catch{notice='기기 내 저장소를 열지 못했습니다. 시크릿 모드나 저장 차단 설정을 확인해 주세요.';}
render();
